- topic_name: "clock"
  #gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- topic_name: "base/command/duty_cycle"
 #gz_topic_name: "base/command/duty_cycle"
  ros_type_name: "actuator_msgs/msg/Actuators"
  gz_type_name: "gz.msgs.Actuators"
  direction: ROS_TO_GZ

# Odometry plugin
- topic_name: "/model/free_flyer/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# Arm joint trajectory
- topic_name: "/model/free_flyer/joint_trajectory"
  ros_type_name: "trajectory_msgs/msg/JointTrajectory"
  gz_type_name: "gz.msgs.JointTrajectory"
  direction: ROS_TO_GZ
  
# topic published by JointState plugin
- topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# gz topic published by DiffDrive plugin
#- ros_topic_name: "odom"
#  gz_topic_name: "odom"
#  ros_type_name: "nav_msgs/msg/Odometry"
#  gz_type_name: "gz.msgs.Odometry"
#  direction: GZ_TO_ROS

# gz topic published by DiffDrive plugin
#- ros_topic_name: "tf"
#  gz_topic_name: "tf"
#  ros_type_name: "tf2_msgs/msg/TFMessage"
#  gz_type_name: "gz.msgs.Pose_V"
#  direction: GZ_TO_ROS

# gz topic subscribed to by DiffDrive plugin
#- ros_topic_name: "cmd_vel"
#  gz_topic_name: "cmd_vel"
#  ros_type_name: "geometry_msgs/msg/Twist"
#  gz_type_name: "gz.msgs.Twist"
#  direction: ROS_TO_GZ


# gz topic published by IMU plugin
#- ros_topic_name: "imu"
#  gz_topic_name: "imu"
#  ros_type_name: "sensor_msgs/msg/Imu"
#  gz_type_name: "gz.msgs.IMU"
#  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (LIDAR)
#- ros_topic_name: "scan"
#  gz_topic_name: "scan"
#  ros_type_name: "sensor_msgs/msg/LaserScan"
#  gz_type_name: "gz.msgs.LaserScan"
#  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (Camera)
#- ros_topic_name: "camera/camera_info"
#  gz_topic_name: "camera/camera_info"
#  ros_type_name: "sensor_msgs/msg/CameraInfo"
#  gz_type_name: "gz.msgs.CameraInfo"
#  direction: GZ_TO_ROS